version: "3.7"
services:

  keycloak:
    image: "jboss/keycloak"
    container_name: "sssp-keycloak"
    restart: always
    environment:
      KEYCLOAK_USER: "${KEYCLOAK_USER}"
      KEYCLOAK_PASSWORD: "${KEYCLOAK_PASSWORD}"
      PROXY_ADDRESS_FORWARDING: "true"
      KEYCLOAK_IMPORT: "/sssp-keycloak/realm-export.json"
    volumes:
      - "./sssp-keycloak:/sssp-keycloak:ro"
  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_SECRET}"

  server:
    image: node
    container_name: server
    restart: always
    depends_on:
      - mongo
    environment:
      DEV_MODE: "true"
      MONGO_USER: "${MONGO_USER}"
      MONGO_SECRET: "${MONGO_SECRET}"
      MONGO: "mongo"
    volumes:
      - "./sssp-server:/sssp-server"
    working_dir: /sssp-server
    command: npm run-script dev

  client:
    image: node
    container_name: client
    restart: always
    environment:
      DEV_MODE: "true"
      PORT: 8080
    stdin_open: true
    tty: true
    volumes:
      - "./sssp-client:/sssp-client"
    working_dir: /sssp-client
    command: npm start

  proxy:
    image: nginx
    container_name: "proxy"
    depends_on:
      - keycloak
      - client
      - server
    restart: always
    volumes:
      - "./sssp-proxy/:/etc/nginx/conf.d/"
    ports:
      - "8080:8080"
