---
# Sample playbook to integrate with ansible

- name: ansible integration sample
  hosts: localhost
  tasks:
    - name: get token keycloak
      uri:
        url: https://test.sssp.local:8000/auth/realms/sssp/protocol/openid-connect/token  
        method: POST
        body_format: form-urlencoded
        validate_certs: no
        body:
          username: test1
          password: Welcome.2020
          scope: openid
          grant_type: password
          client_id: sssp-client
      register: result

    - name: print the token
      debug:
        msg: "{{ result.json.access_token }}"

    - name: get services from backend
      uri:
        url: https://test.sssp.local:8000/graphql
        method: POST
        validate_certs: no
        headers:
          Authorization: 'bearer {{ result.json.access_token }}'
        body_format: json
        body:
          query: '{{ lookup("template", "./get_services.graphql") }}'
      register: services

    - name: print the services
      debug:
        msg: "{{ services.json.data }}"
